name: Issue Labeled

# Runs when an issue is labeled
on:
  issues:
    types:
      - labeled
      - edited

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: echo "${{ toJson(github.event) }}"
  pkg_req_new:
    if: github.event.label.name == 'pkg_req_new'
    uses: Snapkg/snapkg/.github/workflows/new_package_request.yml@main
    permissions:
      issues: write
    with:
      issue_number: ${{ github.event.issue.number }}
      issue_body: ${{ github.event.issue.body }}
    secrets:
      SNAPKG_BOT_TOKEN: ${{ secrets.SNAPKG_BOT_TOKEN }}
      
