name: New Issue Submitted

# Runs when a new issue is opened
on:
  issues:
    types:
      - labeled

jobs:
  pkg_req_new:
    if: github.event.label.name == 'pkg_req_new'
    uses: Snapkg/snapkg/.github/workflows/new_issue_label_pkg_req_new.yml@main
    with:
      issue: ${{ github.event.issue }}
