name: New Package Request

# Runs when a new issue is opened
on:
  workflow_call:
    inputs:
      issue:
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue labels
      run: |
        echo success && echo ${{inputs.issue.body}}
