name: New Package Request

# Runs when a new issue is opened
on:
  workflow_call:
    inputs:
      issue_number:
        type: string
        required: true
      issue_body:
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Validate manifest JSON
      run: |
        md=$(cat << 'EOF' "${{ inputs.issue_body }}")
        manifest=$(echo "$md" | awk '/## Package manifest/{flag=1; next} /^```javascript$/{flag=1; next} flag; /^```$/{flag=0}' | sed -e '1d; $d') &&
        echo "$md"
