name: New Package Request

# Runs when a new issue is opened
on:
  workflow_call:
    inputs:
      issue_number:
        type: string
        required: true
      issue_body:
        type: string
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Validate manifest JSON
      run: |
        echo success && echo "${{inputs.issue_body}}"
